# Uncomment this line to define a global platform for your project
platform :ios, "8.0"

target 'FashionNewsFeed' do
pod 'AFNetworking', '~> 2.5.0'
pod 'DateTools'
pod 'HTMLReader'
pod 'GTScrollNavigationBar'
pod 'VK-ios-sdk'
pod "FBSDKCoreKit"
pod "FBSDKShareKit"

end

target 'FashionNewsFeedTests' do
pod 'AFNetworking', '~> 2.5.0'
pod 'DateTools'
pod 'HTMLReader'
pod 'GTScrollNavigationBar'
pod 'VK-ios-sdk'
pod "FBSDKCoreKit"
pod "FBSDKShareKit"

end



